### ISSUE TITLE
queryInvoiceStatus() test failed

### ISSUE THREAD

**Issue by adamteglas** [angro-kft/nav-connector#62]
Az alábbi hibát írja teszt futtatás után:

> 1) queryInvoiceStatus()
>        "before all" hook: before:
>      Error: An invoice is still under processing!
>       at retry (test/lib/wait-invoice-processing.js:81:15)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:188:7)

A NAV felületén pedig ezt írja gondnak:
> A megadott számlaszám egynél többször szerepel a kérésben
> - Field [productCodes] contains error: [Invalid content was found starting with element 'productCodes'. One of '{"http://schemas.nav.gov.hu/OSA/1.0/data":lineNumber}' is expected.]

**Comment by kailniris** [comment]
A hibát azért írja mert, a NAV online számla rendszere jelenleg nagy késéssel dolgozza fel a beküldött számlákat.
A queryInvoiceStatus() teszt before all hook-jában beküld pár számlát amiken majd a státusz lekérdezéseket lehet tesztelni. Ezen számlák között vannak direkt hibásan elkészítettek is, hogy tesztelni lehessen a hibás számlák lekérdezése során történő kódok működését is, pl típus konverzió. Ezért lehet látni a beküldés során hibás számlát az online felületen.
A NAV online számla szolgáltatás jelenlegi állapotában nem fog lefutni a queryInvoiceStatus() és queryInvoiceData() tesztek mivel a számla feldolgozás csak napokra rá történik meg.

Az aktuális (3.0.1) verzió mely támogatja a NAV online számla 0.15-os verzióját, lefutott tesztjei megtekinthetőek a [circleci](https://circleci.com/gh/angro-kft/nav-connector/163) felületén.

**Comment by adamteglas** [comment]
Nagyon köszi a választ, btw "Isten-Király" a cucc! :)
